use std::{collections::BTreeMap, io::Read};

use serde::Deserialize;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ZoneMapping {
    /// Exact `zone` value emitted by WizRust101-DB.
    pub location: String,
    /// The DB's exact world label; `Unknown` is represented as absent.
    pub world: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
struct DbZone {
    world: String,
    zone: String,
}

#[derive(Debug, thiserror::Error)]
pub enum MappingError {
    #[error("could not read mapping source: {0}")]
    Io(#[from] std::io::Error),
    #[error("invalid WizRust101-DB zones.json: {0}")]
    Json(#[from] serde_json::Error),
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct ZoneCatalog {
    pub zones: BTreeMap<String, ZoneMapping>,
}

impl ZoneCatalog {
    pub fn from_reader(reader: impl Read) -> Result<Self, MappingError> {
        let zones: BTreeMap<String, DbZone> = serde_json::from_reader(reader)?;
        let zones = zones
            .into_iter()
            .map(|(path, db_zone)| {
                let world = (db_zone.world != "Unknown").then_some(db_zone.world);
                (
                    path,
                    ZoneMapping {
                        location: db_zone.zone,
                        world,
                    },
                )
            })
            .collect();
        Ok(Self { zones })
    }

    pub fn resolve(&self, canonical_zone_path: &str) -> Option<&ZoneMapping> {
        self.zones.get(canonical_zone_path)
    }
}

/// Builds from the checked-in output generated by WizRust101-DB. Runtime never
/// reaches the network and does not duplicate DB resolution rules.
pub fn runtime_catalog() -> Result<ZoneCatalog, MappingError> {
    ZoneCatalog::from_reader(include_bytes!("../vendor/zones.json").as_slice())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_exact_db_names_and_omits_unknown_worlds() {
        let catalog = ZoneCatalog::from_reader(
            r#"{"A/known":{"world":"Wizard City","zone":"The Commons"},"A/unknown":{"world":"Unknown","zone":"Internal_Fallback"}}"#.as_bytes(),
        ).unwrap();
        assert_eq!(catalog.resolve("A/known").unwrap().location, "The Commons");
        assert_eq!(
            catalog.resolve("A/known").unwrap().world.as_deref(),
            Some("Wizard City")
        );
        assert_eq!(
            catalog.resolve("A/unknown").unwrap().location,
            "Internal_Fallback"
        );
        assert_eq!(catalog.resolve("A/unknown").unwrap().world, None);
    }

    #[test]
    fn bundled_db_catalog_loads() {
        assert!(runtime_catalog().unwrap().zones.len() > 3000);
    }
}
